// Generated by Haxe 4.1.3
package _EnumValue;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class EnumValue_Impl_
{
	public static boolean match(java.lang.Object this1, java.lang.Object pattern)
	{
		//line 59 "C:\\HaxeToolkit\\haxe\\std\\EnumValue.hx"
		return false;
	}
	
	
}


